### ISSUE TITLE
Add a license to getfonts

### ISSUE THREAD

**Issue by chee** [DavidBarts/getfonts#1]
Hey!

i notice you don't have a license in here, so it's implicitly copyright to you only. could you tell me what license this code is under? i want to use it in a project

**Comment by chrismlarson** [comment]
Agreed. @DavidBarts could you let us know if we can use this code?

**Comment by chrismlarson** [comment]
@chee did you end up with a different solution to this?

**Comment by DavidBarts** [comment]
Thanks for pestering me about this! Just added a license. I'm happy that one of the things I have here is proving useful to others.

**Comment by chrismlarson** [comment]
Appreciated! I know how it is looking at old projects. Hope you are safe and healthy!
